version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
  build:
    commands:
      - echo Building Docker image...
      - docker build -t flask-app .
  post_build:
    commands:
      - echo Build completed successfully.
artifacts:
  files:
    - '**/*'
  discard-paths: yes
  base-directory: app
