name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        pip install -r app/requirements.txt

    - name: Install AWS CDK dependencies
      run: |
        pip install aws-cdk-lib constructs

    - name: Run tests
      run: |
        export PYTHONPATH=$(pwd)/app
        pytest tests/

    - name: Install AWS CDK
      run: npm install -g aws-cdk

    - name: Deploy with CDK
      run: |
        # Ensures that public access is blocked in CDK stack definition
        cdk bootstrap
        cdk deploy --require-approval never
               
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: "us-east-1"

